-------------------------------------------------------------------------------
Test set: at.htl.beeyond.integration.application.custom.CustomApplicationTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.221 s <<< FAILURE! - in at.htl.beeyond.integration.application.custom.CustomApplicationTest
testCreateCustomApplication  Time elapsed: 9.219 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource at.htl.beeyond.integration.util.DatabaseResource@5180d11
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:10.5, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}


